openapi: 3.0.0
info:
  title: Temp Feel API
  description: API for predicting comfort feeling and recommending clothing based on input features
  version: 2.0.0

servers:
  - url: http://localhost:8080
    description: Local development server
  - url: https://temp-feel-api.vercel.app
    description: Production server

paths:
  /predict/feels:
    post:
      summary: Predict comfort feelings based on input features
      description: Returns a prediction of comfort feelings based on environmental and personal conditions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                instances:
                  type: array
                  items:
                    type: object
                    properties:
                      t_dress:
                        type: number
                        description: Presence of dress tee
                        example: 0
                      t_poly:
                        type: number
                        description: Presence of polyester tee
                        example: 1
                      t_cot:
                        type: number
                        description: Presence of cotton tee
                        example: 0
                      sleeves:
                        type: number
                        description: Presence of sleeves
                        example: 1
                      j_light:
                        type: number
                        description: Presence of light jacket
                        example: 0
                      j_fleece:
                        type: number
                        description: Presence of fleece jacket
                        example: 0
                      j_down:
                        type: number
                        description: Presence of down jacket
                        example: 0
                      shorts:
                        type: number
                        description: Presence of shorts
                        example: 0
                      p_thin:
                        type: number
                        description: Presence of thin pants
                        example: 0
                      p_thick:
                        type: number
                        description: Presence of thick pants
                        example: 0
                      p_fleece:
                        type: number
                        description: Presence of fleece pants
                        example: 0
                      p_down:
                        type: number
                        description: Presence of down pants
                        example: 0
                      temp:
                        type: number
                        description: Temperature in Celsius
                        example: 25
                      sun:
                        type: number
                        description: Sun intensity (0-1)
                        example: 0
                      headwind:
                        type: number
                        description: Headwind speed
                        example: 0
                      snow:
                        type: number
                        description: Snow intensity (0-1)
                        example: 0
                      rain:
                        type: number
                        description: Rain intensity (0-1)
                        example: 0
                      fatigued:
                        type: number
                        description: Fatigue level (0-1)
                        example: 0
                      hr:
                        type: number
                        description: Heart rate
                        example: 75
      responses:
        '200':
          description: Successful prediction
          content:
            application/json:
              schema:
                type: object
                properties:
                  prediction:
                    type: string
                    description: The predicted feeling class
                    example: 'warm'
                  probabilities:
                    type: array
                    items:
                      type: object
                    description: Probability scores for each class
                    example: [{0: 0.3099999725818634, 1: 0.6399998664855957, 2: 0.04999999701976776, 3: 0.0}]
                  accuracy:
                    type: number
                    description: Model accuracy
                    example: 0.6470588235294118
        '400':
          description: Bad request - invalid input
        '500':
          description: Internal server error